/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./about.html",
    "./initiatives.html",
    "./blood-centres.html",
    "./gallery.html",
    "./contact.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f3faff",
        "outline-variant": "#e4beba",
        "error-container": "#ffdad6",
        "surface-tint": "#455a64",
        "inverse-on-surface": "#dff4ff",
        "surface-container-highest": "#cfe6f2",
        "on-background": "#071e27",
        "primary-fixed": "#cfd8dc",
        "surface-dim": "#c7dde9",
        "secondary": "#1565C0",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-surface": "#071e27",
        "on-primary-container": "#eceff1",
        "on-tertiary-container": "#e5e8eb",
        "on-primary-fixed": "#10191d",
        "surface-container": "#dbf1fe",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#37474f",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-container": "#64a1ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#65686b",
        "primary-fixed-dim": "#90a4ae",
        "tertiary-fixed": "#e0e3e6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#44474a",
        "on-surface-variant": "#5b403d",
        "on-secondary-container": "#003670",
        "secondary-fixed": "#d6e3ff",
        "surface-bright": "#f3faff",
        "on-secondary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#00468c",
        "inverse-primary": "#90a4ae",
        "primary": "#37474f",
        "brand-red": "#C62828",
        "brand-red-hover": "#B71C1C",
        "brand-blue": "#1565C0",
        "brand-green": "#2E7D32",
        "inverse-surface": "#1e333c",
        "secondary-fixed-dim": "#a9c7ff",
        "outline": "#8f706c",
        "tertiary": "#4d5053",
        "on-tertiary-fixed": "#191c1e",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-variant": "#cfe6f2",
        "surface-container-low": "#e6f6ff",
        "background": "#f3faff",
        "primary-container": "#455a64",
        "surface-container-high": "#d5ecf8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "container-max": "1280px",
        "stack-lg": "48px",
        "unit": "8px",
        "stack-sm": "8px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
